# config.py

LASTFM_API_KEY = "YOUR_LASTFM_API_KEY"
LASTFM_API_SECRET = "YOUR_LASTFM_API_SECRET"
ACOUSTID_API_KEY = "YOUR_ACOUSTID_API_KEY"

WIFI_SSID = "Vinyl-Bot"
WIFI_SECURITY = "WPA"
COUNTRY_CODE = "US"

MUSICBRAINZ_USER_AGENT = ("Vinyl-Bot", "1.0", "contact@example.com")
